cd download_scripts/ESO243-49/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/Holmberg_II/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/Holmberg_IX/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/IC10/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/IC342/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M101/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M31/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M33/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M51/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M81/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M82/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/M83/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC1042/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC1313/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC1365/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC247/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC253/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC300/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC4395/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC4559/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC4945/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC5204/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC5408/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC55/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC5585/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC5907/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC6643/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC6946/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC7090/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC7793/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/NGC925/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/SMC_X-3/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/SS433/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/Swift_J0243.6+6124/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/UGC6456/
./uvotsource_all.sh & 
cd ../..
cd download_scripts/V404Cyg/
./uvotsource_all.sh & 
cd ../..
